# Generated by Django 4.2.6 on 2023-10-14 21:44

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Analysis name')),
                ('type', models.CharField(choices=[('quantitative', 'Quantitative'), ('qualitative', 'Qualitative')], max_length=12, verbose_name='Type of Analysis')),
                ('analysis_date', models.DateField(verbose_name='Analysis date')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnosis')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('type', models.CharField(choices=[('quantitative', 'Quantitative'), ('qualitative', 'Qualitative')], max_length=12, verbose_name='Type of Analysis')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF00', image_field=None, max_length=25, samples=None, verbose_name='Background Color')),
                ('text_color', colorfield.fields.ColorField(default='#000000FF', image_field=None, max_length=25, samples=None, verbose_name='Text Color')),
                ('processing_model', models.CharField(blank=True, choices=[('mri', 'MRI'), ('pneumonia_detection', 'Pneumonia detection')], help_text='Leave empty if no suitable model available. Does not work for type "Quantitative"', max_length=20, null=True, verbose_name='Choose model for processing')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuantitativeAnalysisEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('value', models.FloatField(verbose_name='Value')),
                ('unit', models.CharField(blank=True, max_length=12, null=True, verbose_name='Unit')),
                ('normal_value', models.FloatField(blank=True, null=True, verbose_name='Normal value')),
                ('analysis_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantitative_analysis_entries', to='analysis.analysisentry', verbose_name='Analysis entry')),
            ],
        ),
        migrations.AddField(
            model_name='analysisentry',
            name='tags',
            field=models.ManyToManyField(to='analysis.analysistag', verbose_name='Tags'),
        ),
    ]
