# Generated by Django 4.2.6 on 2023-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistag',
            name='processing_model',
            field=models.CharField(blank=True, choices=[('trumor_detection', 'Trumor detection'), ('pneumonia_detection', 'Pneumonia detection')], help_text='Leave empty if no suitable model available. Does not work for type "Quantitative"', max_length=20, null=True, verbose_name='Choose model for processing'),
        ),
        migrations.AlterField(
            model_name='quantitativeanalysisentry',
            name='normal_value',
            field=models.TextField(blank=True, null=True, verbose_name='Normal value'),
        ),
    ]
