# Generated by Django 4.2.6 on 2023-10-14 07:16

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/Lenovo/PycharmProjects/president_tech_award/media/medical_certificates'), verbose_name='File'),
        ),
    ]
