# Generated by Django 4.2.6 on 2023-10-14 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical_tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_tests', '0003_alter_medicalcertificate_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='medicalcertificate',
            name='file',
            field=models.FileField(upload_to=medical_tests.models.MedicalCertificate.user_directory_path, verbose_name='File'),
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=medical_tests.models.Vaccine.user_directory_path, verbose_name='File')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('received_date', models.DateTimeField(verbose_name='Received date')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration date')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='medical_institutions.medicalinstitution', verbose_name='Given by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_tests.vaccinetype', verbose_name='Vaccine type')),
            ],
            options={
                'order_with_respect_to': 'owner',
            },
        ),
    ]
