# Generated by Django 4.2.6 on 2023-10-15 05:30

from django.db import migrations, models
import medical_tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_tests', '0007_alter_vaccine_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='file',
            field=models.FileField(upload_to=medical_tests.models.Vaccine.user_directory_path, verbose_name='File'),
        ),
    ]
